### ISSUE TITLE
Using with Express server

### ISSUE THREAD

**Issue by joaocunha** [jgconway/pug-include-glob#1]
Any way to use this with an Express server (not explicitly calling `pug.renderFile()`)?

**Comment by conelton** [comment]
When Express invokes Pug to render a view, the parameters you pass to `res.render()` are passed by Pug to `pug.renderFile()`, so the usage should be exactly the same, i.e. `res.render('filename', { plugins: [ pugIncludeGlob() ] })`.

**Comment by joaocunha** [comment]
Super! It does work! Thank you :)
