### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by joaocunha** [jgconway/pug-include-glob#2]
I understand walking over ASTs can get pretty expensive, but do you think there's room for decent improvements on https://github.com/conelton/pug-include-glob/blob/master/src/index.js#L33-L44?

Our build times became 2 or 3 times slower (around 30s now) - it's not an issue on an Express server, but we also compile pug files to both test the output HTML and to serve them on static servers (we have around 120 pug source files).

Just so you better get our scenario, we wanted to use the plugin to include pug mixins globally, like so:

```
include ./atoms/**/*
include ./molecules/**/*
include ./organisms/**/*
include ./utils/**/*
```

I'm happy to help if you can give some pointers!

**Comment by conelton** [comment]
This plugin was published before the Pug maintainers had released any documentation for the pug-walk module, so it was never going to be an optimal solution. Since that documentation is now available, I'll see if there are any obvious improvements that could be made.

Are you only using globby includes in the top-level templates? If so, perhaps a maximum file depth option would be useful; so that only files known to contain globby includes are walked. Let me know if that would be a useful feature - it shouldn't be too difficult to implement.

**Comment by joaocunha** [comment]
@conelton awesome!

Yes, only top-level. Think of it as a `base.scss` file, where you could just `@import mixins/**/*`.

**Comment by joaocunha** [comment]
```
├── mixins
│   ├── atoms
│   │   ├── a-box.pug
│   │   ├── a-button-link.pug
│   │   ├── a-fieldset.pug
│   │   ├── a-figure-cation.pug
│   │   ├── a-figure.pug
│   │   ├── a-footer.pug
│   │   ├── a-iframe.pug
│   │   ├── a-label.pug
│   │   ├── a-member-avatar.pug
│   │   ├── a-member-identity.pug
│   │   ├── a-member-location.pug
│   │   ├── a-member-nickname.pug
│   │   ├── a-member-stats.pug
│   │   ├── a-member-tagline.pug
│   │   ├── a-member-time-ago.pug
│   │   ├── a-page-break.pug
│   │   ├── a-pill.pug
│   │   └── a-switch.pug
│   ├── head.pug
│   ├── molecules
│   │   ├── m-card-member-info.pug
│   │   ├── m-checkbox-w-label.pug
│   │   ├── m-member-card.pug
│   │   ├── m-member-info.pug
│   │   └── m-select.pug
│   ├── organisms
│   │   ├── o-nav.pug
│   │   ├── o-page-header.pug
│   │   ├── o-pictures.pug
│   │   ├── o-profile-header.pug
│   │   ├── o-sidebar.pug
│   │   ├── o-story.pug
│   │   ├── o-subnav.pug
│   │   ├── o-videos.pug
│   │   └── o-writing.pug
│   ├── utils
│   │   └── number-with-delimiter.pug
│   └── vinyl.pug // <----------------------- This includes all mixins, making them available
                  // ------------------------ on the templates.
├── profile__about.pug
├── profile__feed.pug
├── profile__pictures.pug
├── profile__videos.pug
├── profile__writings.pug
...
```

**Comment by conelton** [comment]
Having read the new docs for the updated pug-walk module, I have made one slight change to the AST transformation (b83a18074ef1711b8c25436cc2c49356ffb6e0ee). I doubt it will have any significant effect on performance.

I also had a look at the possibility of adding a file depth limit option, and I've hit a snag. The Pug API doesn't seem to provide that kind of contextual information to plugins. I can't see any way for the plugin to know how deep into the dependency structure it is at any given time. It's possible that it could be hacked together, but there's no way it would be robust. I'll keep looking and perhaps open an issue on the relevant Pug module to see if such a feature could be added.

**Comment by joaocunha** [comment]
@conelton indeed, I can't notice any performance improvement yet. Thanks for putting effort into this, tho! I'm watching the repo just so anything changes.

Thanks!

**Comment by conelton** [comment]
pugjs/pug#2568

**Comment by conelton** [comment]
@joaocunha In the meantime, I have added an option which allows files to be selectively ignored by the plugin. Hopefully this can be useful to you. Let me know how it impacts performance.
